### ISSUE TITLE
Change License to "AGPL-3.0-only" or "AGPL-3.0-or-later"

### ISSUE THREAD

**Issue by nrod80** [winkjs/wink-bm25-text-search#14]
The "AGPL-3.0" license currently used in this module (as well as in other Wink modules) is [marked as deprecated by SPDX](https://spdx.org/licenses/). The current valid identifiers are "AGPL-3.0-only" and "AGPL-3.0-or-later". According to SPDX,

> Release 3.0 replaced previous Identifiers for GNU licenses with more explicit Identifiers to reflect the “this version only” or “any later version” option specific to those licenses. As such, the previously used Identifiers for those licenses are deprecated as of v3.0.

Using the deprecated "AGPL-3.0" license identifier causes this module to be flagged as a vulnerability in tools like [Snyk](https://snyk.io/).

**Comment by rachnachakraborty** [comment]
Hi @nrod80 
Thanks for highlighting! Shall review this and action.

Best,
Rachna

**Comment by sanjayaksaxena** [comment]
Hi @nrod80,

We have switched to MIT license for wink packages, details at http://winkjs.org/blog/a-more-permissive-license.html.

Thanks for your support.

Best 
Sanjaya
