### ISSUE TITLE
Consider instantiating bm25fIMS when setting module.exports

### ISSUE THREAD

**Issue by prtksxna** [winkjs/wink-bm25-text-search#6]
Like express (HTTP server), and unlike other wink libraries, bm25 needs to be *instantiated* before using.

### Express
```js
var express = require('express');
var app = express();
```

### NBC
```js
var bm25 = require( 'wink-bm25-text-search' )();
```

***
In our source code, could we:

```js
module.exports = bm25fIMS();
```

The function doesn't have any arguments so there aren't two ways of doing this any way.

**Comment by sanjayaksaxena** [comment]
It is required to aid user if s/he needs more than one instance; plus in  future it may accept arguments for some additional behavior. In the example `require( 'wink-bm25-text-search' )`**`()`** is a shortcut!

**Comment by prtksxna** [comment]
I have a feeling that someone might miss the extra `()` (while writing their own code), we should at least split it in two lines, like in the case of express.

**Comment by sanjayaksaxena** [comment]
Updated clearly in the example section of README.
